config/routes.rb
Task::Application.routes.draw do
  resources :clients
  resources :employees
  resources :projects
  devise_for :users
  root 'home#index'
  get 'income' => "projects#income"
  get 'expenses'=> 'projects#expenses'

end

app/models/client.rb
class Client < ActiveRecord::Base
	belongs_to :project
       
        validates :name, :project_id, presence: true
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_one :project
	has_one :client, :through => "project"

 	validates :first_name, :last_name, :email, :emp_id, presence: true
	validates :email, format: { with: /\A[a-zA-Z]+\z/, message: "valid email opnly" }

        def full_name
		"#{first_name} #{last_name}"
	end 
end

app/models/project.rb
class Project < ActiveRecord::Base	
	belongs_to :employee
	has_one :client

        validates :title, :employee_id, presence: true
        validates :income, :expense, numericality: true	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable	 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    if current_user.present?
      @clients = Client.all
      respond_with(@clients)
    else
      redirect_to '/users/sign_in'
    end    
  end

  def show
    if current_user.present?
      respond_with(@client)
    else
      redirect_to '/users/sign_in'
    end   
  end

  def new
    if current_user.present?
      @client = Client.new
      respond_with(@client)
    else
      redirect_to '/users/sign_in'
    end     
  end

  def edit
  end

  def create
    if current_user.present?
      @client = Client.new(client_params)
      @client.save
      respond_with(@client)
    else
      redirect_to '/users/sign_in'
    end     
  end

  def update
    if current_user.present?
      @client.update(client_params)
      respond_with(@client)
    else
      redirect_to '/users/sign_in'
    end 
  end

  def destroy
    if current_user.present?
      @client.destroy
      respond_with(@client)  
    else
      redirect_to '/users/sign_in'
    end 
  end

  private
    def set_client
      @client = Client.find(params[:id])
    end

    def client_params
      params.require(:client).permit(:name)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    if current_user.present?
      @employees = Employee.all
      respond_with(@employees)
    else
      redirect_to '/users/sign_in'
    end
  end

  def show
    if current_user.present?
      respond_with(@employee)
    else
      redirect_to '/users/sign_in'
    end   
  end

  def new
    if current_user.present?
      @employee = Employee.new
      respond_with(@employee)
    else
      redirect_to '/users/sign_in'
    end      
  end

  def edit
  end

  def create
    if current_user.present?
      @employee = Employee.new(employee_params)
      @employee.save
      respond_with(@employee)
    else
      redirect_to '/users/sign_in'
    end      
  end

  def update
    if current_user.present?
      @employee.update(employee_params)
      respond_with(@employee)
    else
      redirect_to '/users/sign_in'
    end      
  end

  def destroy
    if current_user.present?
      @employee.destroy
      respond_with(@employee)
    else
      redirect_to '/users/sign_in'
    end  
    
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :emp_id, :location, :project_id, :email)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
     unless current_user.present?
       redirect_to '/users/sign_in'
     end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    if current_user.present?
      @projects = Project.all
      respond_with(@projects)
    else
      redirect_to '/users/sign_in'
    end      
  end

  def show
    if current_user.present?      
      respond_with(@project)
    else
      redirect_to '/users/sign_in'
    end      
  end

  def new
    if current_user.present?
      @project = Project.new
      respond_with(@project)
    else
      redirect_to '/users/sign_in'
    end      
  end

  def edit
  end

  def create
    if current_user.present?
       @project = Project.new(project_params)
       @project.save
       respond_with(@project)
    else
      redirect_to '/users/sign_in'
    end         
  end

  def update
     if current_user.present?
       @project.update(project_params)
       respond_with(@project)
    else
      redirect_to '/users/sign_in'
    end     
  end

  def destroy
    if current_user.present?
       @project.destroy
       respond_with(@project)
    else
      redirect_to '/users/sign_in'
    end     
  end
  
  def income
    if current_user.present?
       @projects = Project.all
       @total_income = Project.all.sum(:income)
    end  
  end 

  def expenses
    if current_user.present?
       @projects = Project.all
       @total_expenses = Project.all.sum(:expense)
    end  
  end 

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:title, :income, :expense, :client_id, :project_desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :project %><br>
    <%= f.collection_select(:project_id, Project.all, :id, :title) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Project</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <% if client.project.title.present? %>
          <td><%= client.project.title %></td>
        <% else %>
          <td> -- </td>
        <% end%>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :emp_id %><br>
    <%= f.text_field :emp_id %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.text_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Emp</th>
      <th>Location</th>
      <th>Project</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.emp_id %></td>
        <td><%= employee.location %></td>
        <td><%= employee.project.title %></td>
        <td><%= employee.email %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @employee.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employee.last_name %>
</p>

<p>
  <strong>Emp:</strong>
  <%= @employee.emp_id %>
</p>

<p>
  <strong>Location:</strong>
  <%= @employee.location %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/home/index.html.erb
<br>
<%= link_to 'Employees', employees_path %>
<br>
<%= link_to 'Clients', clients_path %>
<br>
<%= link_to 'Projects', projects_path %>
<br>
<%= link_to 'Income', employees_path %>
<br>
<%= link_to 'Expenses', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Task</title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
<div class="container">
		<form class="form-horizontal">
			<fieldset>    
				<%= yield %>
			</fieldset>
		</form>
</div>
	</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :income %><br>
    <%= f.text_field :income %>
  </div>
  <div class="field">
    <%= f.label :expense %><br>
    <%= f.text_field :expense %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.collection_select(:employee_id, Employee.all, :id, :full_name) %>
  </div>
  <div class="field">
    <%= f.label :project_desc %><br>
    <%= f.text_area :project_desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/expenses.html.erb
<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Expenses</th>            
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.expense %></td> 	    
      </tr>
    <% end %>
       <tr>
          <td><b>Total Expenses</b></td> 
          <td><b><%= @total_expenses %></b></td> 
       </tr>
  </tbody>
</table>

app/views/projects/income.html.erb
<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Income</th>            
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.income %></td> 	    
      </tr>
    <% end %>
       <tr>
          <td><b>Total Income</b></td> 
          <td><b><%= @total_income %></b></td> 
       </tr>
  </tbody>
</table>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Income</th>
      <th>Expense</th>
      <th>Client</th>
      <th>Project desc</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.income %></td>
        <td><%= project.expense %></td>
        <td><%= project.client.name %></td>
        <td><%= project.project_desc %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Income:</strong>
  <%= @project.income %>
</p>

<p>
  <strong>Expense:</strong>
  <%= @project.expense %>
</p>

<!--<p>
  <strong>Client:</strong>
  <%# @project.client_id %>
</p> -->

<p>
  <strong>Project desc:</strong>
  <%= @project.project_desc %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>